WebApplication1/Controllers/CorrectionDeleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WebApplication1.Models;
using System.Data.Entity;

using System.Threading.Tasks;
using System.IO;
//using System.Data;

namespace WebApplication1.Controllers
{
    public class CorrectionDeleteController : Controller
    {
        //context as db
        private Sqlsvr db = new Sqlsvr();
        InputCheck ck = new InputCheck();
        ExceptionLog el = new ExceptionLog();

        // GET: CorrectionDelete
        public ActionResult InitialCoDe()
        {

            try
            {
                var flashcards = db.Flashcards.ToList();
                return View(flashcards);
            }
            catch (Exception exception)
            {
                el.writeLod(exception.ToString());
                return View("MainController");
            }

        }

        // GET: CorrectionDelete
        [HttpPost]
        public ActionResult Delete(int id)
        {

            try
            {
                //削除対象を検索
                Flashcard flashcards = db.Flashcards.Find(id);
                return View(flashcards);
            }
            catch (Exception exception)
            {
                el.writeLod(exception.ToString());
                return View("MainController");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                //削除対象を取得・削除・保存
                Flashcard flashcard = db.Flashcards.Find(id);
                db.Flashcards.Remove(flashcard);
                db.SaveChanges();
                //InitialCoDe();
                var flashcards = db.Flashcards.ToList();

                ViewData["msg"] = "削除を完了しました。";
                return View("InitialCoDe", flashcards);
            }
            catch (Exception exception)
            {
                el.writeLod(exception.ToString());
                return View("MainController");
            }

        }


        [HttpPost]
        public ActionResult Edit(int id)
        {
            //指定したidの値を取得
            Flashcard flashcards = db.Flashcards.Find(id);
            return View(flashcards);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditComp(Flashcard flashcard)
        {
            if (ModelState.IsValid)
            {
                //入力チェック
                string inpCk = ck.word(flashcard.Word, flashcard.Meaning, flashcard.Remarks);

                if (inpCk != "OK")
                {
                    ViewData["msg"] = inpCk;
                    Edit(flashcard.ID);
                    return View("Edit");
                }

                //重複登録チェック
                string sameCkUp = ck.sameCkUp(flashcard.ID, flashcard.Word);

                if (sameCkUp != "OK")
                {
                    ViewData["msg"] = sameCkUp;
                    Edit(flashcard.ID);
                    return View("Edit");
                }


                try
                {
                    //更新であることを明示
                    db.Entry(flashcard).State = EntityState.Modified;
                    db.SaveChanges();

                    InitialCoDe();
                    ViewData["msg"] = "修正を完了しました。";
                    return View("InitialCoDe");
                }
                catch (Exception exception)
                {
                    el.writeLod(exception.ToString());
                    return View("MainController");
                }

            }
            
            return View(flashcard);
        }


        // GET: btnSearch
        [HttpPost]
        public ActionResult BtnSearch(string word)
        {

            if (string.IsNullOrEmpty(word))
            {
                InitialCoDe();
                return View("InitialCoDe");
            }

            try
            {
                // デフォルトではすべてのデータを取得
                var flashcards = from a in db.Flashcards select a;
                flashcards = flashcards.Where(a => a.Word.Contains(word));

                return View("InitialCoDe", flashcards);
            }
            catch (Exception exception)
            {
                el.writeLod(exception.ToString());
                return View("MainController");
            }

        }

    }
}

WebApplication1/Views/CorrectionDelete/Delete.cshtml
@model WebApplication1.Models.Flashcard
@{

}
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="~/Script/jquery-3.3.1.js"></script>
    <script type="text/javascript">
        $(function () {
            if ($('#textWord').val().length == 0) {
                $('#submit').attr('disabled', 'disabled');
            }
            $('#textWord').bind('keydown keyup keypress change', function () {
                if ($(this).val().length > 0) {
                    $('#submit').removeAttr('disabled');
                } else {
                    $('#submit').attr('disabled', 'disabled');
                }
            });
        });
    </script>

    <script type="text/javascript">

<!--

        function check() {

            if (window.confirm('削除してよろしいですか？')) { // 確認ダイアログを表示

                return true; // 「OK」時は送信を実行

            }
            else { // 「キャンセル」時の処理

                window.alert('キャンセルされました'); // 警告ダイアログを表示
                return false; // 送信を中止

            }

        }

        // -->
    </script>


    <title>Delete</title>
</head>
<body>
    <div align="center">

        <h3>削除確認画面</h3>


        <dl class="dl-horizontal">

            <dt>ID：@Model.ID </dt>

            <dt>単語：@Model.Word</dt>

            <dt>意味：@Model.Meaning</dt>

            <dt>備考：@Model.Remarks</dt>

        </dl>

        <form method="post" onSubmit="return check()">

            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="削除" class="btn btn-default" id="delete" formaction="DeleteConfirmed" />
                <input type="hidden" name="id" value="@Model.ID" />
                <input type="button" value="戻る" onclick="location.href='@Url.Action("InitialCoDe", "CorrectionDelete")'">
            </div>
        </form>

        <script>
            document.myform.btn.addEventListener('click', function () {
                var result = window.confirm('送信しても宜しいですか？');

                if (result) {

                    //「true」の処理

                }
                else {

                    //「false」の処理

                }
            })
        </script>

    </div>
</body>
</html>

WebApplication1/Views/CorrectionDelete/Edit.cshtml
@{
    Layout = null;
}

@model WebApplication1.Models.Flashcard
@{}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="~/Script/jquery-3.3.1.js"></script>
    <script type="text/javascript">
        $(function () {
            if ($('#textWord').val().length == 0) {
                $('#submit').attr('disabled', 'disabled');
            }
            $('#textWord').bind('keydown keyup keypress change', function () {
                if ($(this).val().length > 0) {
                    $('#submit').removeAttr('disabled');
                } else {
                    $('#submit').attr('disabled', 'disabled');
                }
            });
        });

    </script>

    <style>
        ul li {
            list-style: none;
            margin-top: 10px;
        }

            ul li.msg {
                margin-bottom: 40px;
            }

        label {
            margin-right: 10px;
            width: 50px;
            float: left;
        }

        ul {
            width: 500px;
            margin: 0 auto;
        }


        input#button {
            display: block;
            margin: 0 auto;
        }
    </style>
    <title>修正画面</title>
</head>
<body>
    <div align="center">

        <h3>修正画面</h3>
        <font color="#ff0000">@ViewData["msg"]</font>

        <form  method="post">

            <!-- csrf対策用のtokenを送付 -->
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <!-- id -->
                <input type="hidden" name="ID" value="@Model.ID" />
                <ul>

                    <!-- word -->
                    <li class="form-group">
                        <label class="control-label col-md-2">単語</label>
                        <div class="col-md-10">
                            <input type="text" name="Word" maxlength="50" size="50" class="form-control" value="@Model.Word" />
                            @Html.ValidationMessageFor(model => model.Word, "", new { @class = "text-danger" })
                        </div>
                    </li>

                    <!-- meaning -->
                    <li class="form-group">
                        <label class="control-label col-md-2">意味</label>
                        <div class="col-md-10">
                            <textarea name="Meaning" cols="50" rows="5" maxlength="250" class="form-control">@Model.Meaning</textarea>
                            @Html.ValidationMessageFor(model => model.Meaning, "", new { @class = "text-danger" })
                        </div>
                    </li>

                    <!-- remarks -->
                    <li class="form-group">
                        <label class="control-label col-md-2">備考</label>
                        <div class="col-md-10">
                            <textarea name="Remarks" cols="50" rows="5" maxlength="250" class="form-control">@Model.Remarks</textarea>
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>
                    </li>

                    <!-- submit -->
                    <li class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="修正" style="width:100px;height:50px" class="btn btn-default" formaction="EditComp"  />
                            <input type="button" value="戻る" style="width:100px;height:50px" onclick="location.href='@Url.Action("InitialCoDe", "CorrectionDelete")'">
                        </div>
                    </li>

                </ul>
            </div>

        </form>
    </div>
</body>
</html>

WebApplication1/Views/CorrectionDelete/InitialCoDe.cshtml
@{
    Layout = null;
}

@model IEnumerable<WebApplication1.Models.Flashcard>
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="C:\Users\h2-ota\source\repos\WebApplication1\jquery-3.3.1.js"></script>
    <title>修正・削除画面</title>
</head>
<body>
    <div align="center">
        <h1>修正・削除画面</h1>

        <div>
            @using (Html.BeginForm(
            "BtnSearch",
            "CorrectionDelete",
            null,
            FormMethod.Post,
            new { enctype = "multipart/form-data" }
            ))
            {
                <b> 単語：</b>
                @Html.TextBox("word", "", new { maxlength = 50, size = 30 })
                <input type="submit" value="検索" />
                <input type="button" value="戻る" onclick="location.href='@Url.Action("Main", "Main")'">
            }
        </div>

    <font color="#ff0000">@ViewData["msg"]</font>

    <h3>一覧</h3>

    <table border="1" class="table" >
        <thead>
            <tr bgcolor="gray">
                <th>ID</th>
                <th>単語</th>
                <th>意味</th>
                <th>備考</th>
                <th>修正</th>
                <th>削除</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.Word</td>
                    <td><pre>@item.Meaning</pre></td>
                    <td><pre>@item.Remarks</pre></td>

                    @using (Html.BeginForm(
                      "Edit",
                      "CorrectionDelete",
                      null,
                      FormMethod.Post,
                      new { enctype = "multipart/form-data" }
                    ))
                    {
                        <td>
                            <input type="submit" value="編集" class="btn btn-default" />
                            <input type="hidden" name="id" value="@item.ID" />
                        </td>
                    }
                    @using (Html.BeginForm(
                     "Delete",
                     "CorrectionDelete",
                     null,
                     FormMethod.Post,
                     new { enctype = "multipart/form-data" }
                   ))
                    {
                        <td>
                            <input type="submit" value="削除" class="btn btn-default" />
                            <input type="hidden" name="id" value="@item.ID" />
                        </td>
                    }

                </tr>
            }
        </tbody>

    </table>
    </div>

</body>
</html>